"""ordered sequence

Revision ID: 916c37b6f706
Revises: 4fddf27dd5e3
Create Date: 2023-12-08 11:17:41.608761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916c37b6f706'
down_revision = '4fddf27dd5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combination_moves', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['combination_id', 'sequence_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combination_moves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
